package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Modern keyboard companion palette: soft neutral surfaces and a restrained indigo accent.
val md_theme_light_primary = Color(0xFF4F55A8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBD1)
val md_theme_light_onPrimaryContainer = Color(0xFF3B0900)
val md_theme_light_secondary = Color(0xFF54586B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE9E2)
val md_theme_light_onSecondaryContainer = Color(0xFF03201B)
val md_theme_light_tertiary = Color(0xFFB86B14) // Amber CRT accent
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDB8)
val md_theme_light_onTertiaryContainer = Color(0xFF2B1700)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8F8FC)
val md_theme_light_onBackground = Color(0xFF1B1B20)
val md_theme_light_surface = Color(0xFFF8F8FC)
val md_theme_light_onSurface = Color(0xFF1B1B20)
val md_theme_light_surfaceVariant = Color(0xFFE3E2EA)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFEDE5D6)
val md_theme_light_inverseSurface = Color(0xFF2C251C)
val md_theme_light_inversePrimary = Color(0xFFFF8A65)
val md_theme_light_surfaceTint = Color(0xFFD9532F)
val md_theme_light_outlineVariant = Color(0xFFC4B8A6)
val md_theme_light_scrim = Color(0xFF000000)

// Retro Dark Scheme Tokens (Cyberpunk CRT Phosphor Green & Amber Terminal)
val md_theme_dark_primary = Color(0xFFC3C5FF)
val md_theme_dark_onPrimary = Color(0xFF1C1E59)
val md_theme_dark_primaryContainer = Color(0xFF353871)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E0FF)
val md_theme_dark_secondary = Color(0xFFC5C4D0)
val md_theme_dark_onSecondary = Color(0xFF2E2E37)
val md_theme_dark_secondaryContainer = Color(0xFF45454F)
val md_theme_dark_onSecondaryContainer = Color(0xFFE2E1EC)
val md_theme_dark_tertiary = Color(0xFFFF6A3D) // Burnt orange diode
val md_theme_dark_onTertiary = Color(0xFF451000)
val md_theme_dark_tertiaryContainer = Color(0xFF651B00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFB5A0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1F24)
val md_theme_dark_onBackground = Color(0xFFE5E1E9)
val md_theme_dark_surface = Color(0xFF1F1F24)
val md_theme_dark_onSurface = Color(0xFFE5E1E9)
val md_theme_dark_surfaceVariant = Color(0xFF303038)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8C5CF)
val md_theme_dark_outline = Color(0xFF92909A)
val md_theme_dark_inverseOnSurface = Color(0xFF101412)
val md_theme_dark_inverseSurface = Color(0xFFE2EFE4)
val md_theme_dark_inversePrimary = Color(0xFF00B02A)
val md_theme_dark_surfaceTint = Color(0xFF39FF14)
val md_theme_dark_outlineVariant = Color(0xFF2D3832)
val md_theme_dark_scrim = Color(0xFF000000)

// Retro Accent Highlights
val RetroAmber = Color(0xFFFFB000)
val RetroCrtGreen = Color(0xFF39FF14)
val RetroOrange = Color(0xFFD9532F)
val RetroTeal = Color(0xFF1B6E60)
val RetroMacGray = Color(0xFFD0D3D4)
val RetroSynthMagenta = Color(0xFFFF007F)
val RetroSynthCyan = Color(0xFF00F0FF)
