"""Deterministic FTRL baseline and word-disjoint synthetic spelling evaluation data.

No curated TypeRight typo maps are read. Regenerate with Python 3, no dependencies.
Synthetic errors are supplemental; authored multilingual/context fixtures remain mandatory.
"""
import collections, hashlib, json, math, pathlib, random
ROOT = pathlib.Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'app/src/main/assets/dictionaries'
FEATURES = ['literal','canonical','distance','similarity','keyboard','frequency','context','personal','accepted','rejected','touch','proposal','contextRule','completion','prefix','suffix','missing','repetition']
def affixes(typed,word):
    p=0
    while p<min(len(typed),len(word)) and typed[p]==word[p]: p+=1
    s=0
    while s<min(len(typed),len(word)) and typed[-1-s]==word[-1-s]: s+=1
    iterator=iter(word)
    missing=len(word)>len(typed) and all(c in iterator for c in typed)
    repetition=typed!=word and ''.join(c for i,c in enumerate(typed) if i==0 or typed[i-1]!=c)==''.join(c for i,c in enumerate(word) if i==0 or word[i-1]!=c)
    return [p/max(1,len(typed)),s/max(1,len(typed)),int(missing),int(repetition)]
def main():
    rng = random.Random(190191)
    canonical = set((ASSETS/'english_canonical.txt').read_text().splitlines())
    freq = {w:int(f) for w,f in (line.split('\t') for line in (ASSETS/'english_frequency.tsv').read_text().splitlines())}
    words = sorted(w for w in canonical if 5 <= len(w) <= 12 and w.isascii() and w.isalpha() and freq.get(w,0) >= 6)
    rows = []
    for word in words:
        split = ['training']*6+['calibration']*2+['holdout']*2
        split = split[int(hashlib.sha256(word.encode()).hexdigest()[:8],16)%10]
        i = rng.randrange(len(word)-1)
        errors = [word[:i]+word[i+1:],word[:i]+word[i+1]+word[i]+word[i+2:],word[:i]+word[i]+word[i:], word[:i]+rng.choice('abcdefghijklmnopqrstuvwxyz')+word[i+1:]]
        for kind,typed in zip(['missing','transpose','repeated','substitution'],errors):
            if typed == word or typed in canonical: continue
            rows.append(dict(typed=typed,expected=word,context=[],kind=kind,split=split))
    # Pairwise FTRL learns generic spelling/frequency features; protected literal controls
    # and feedback channels provide positive and negative supervised examples.
    z=[0.0]*len(FEATURES); n=[0.0]*len(FEATURES)
    def weights():
        return [0.0 if abs(v)<=.01 else -(v-math.copysign(.01,v))/((1+math.sqrt(n[i]))/.25+.25) for i,v in enumerate(z)]
    def update(chosen,other):
        w=weights(); x=[a-b for a,b in zip(chosen,other)]
        score=sum(a*b for a,b in zip(w,x)); err=1/(1+math.exp(-max(-20,min(20,score))))-1
        for i,xx in enumerate(x):
            g=err*xx; z[i]+=g-(math.sqrt(n[i]+g*g)-math.sqrt(n[i]))/.25*w[i]; n[i]+=g*g
    training=[r for r in rows if r['split']=='training']
    for epoch in range(8):
        rng.shuffle(training)
        for row in training:
            length=len(row['typed']); f=min(1,math.log1p(freq[row['expected']])/12)
            correct=[0,1,1,1-1/max(3,length),.15,f,0,0,0,0,0,0,0,0]+affixes(row['typed'],row['expected'])
            literal=[1,0,0,1,0,min(1,math.log1p(freq.get(row['typed'],0))/12),0,0,0,0,0,0,0,0]+[1,1,0,0]
            update(correct,literal)
            # Nearby canonical alternative: longer edits and lower usage are weaker evidence.
            update(correct,[0,1,2,1-2/max(3,length),.30,max(0,f-.25),0,0,0,0,0,0,0,0]+[.2,.2,0,0])
            # Correct text must win against a frequent neighbouring word.
            update([1,1,0,1,0,f,0,0,0,0,0,0,0,0]+[1,1,0,0],correct)
            # Evidence channels train on labels independently of specific word identities.
            channel=rng.choice([6,7,8,10,11,12])
            a=correct.copy(); b=correct.copy(); a[channel]=1; update(a,b)
            a=correct.copy(); a[9]=1; update(correct,a)
            a=correct.copy(); a[13]=1; update(correct,a)
            # Strong span rules must overcome literal evidence even for two-edit homophones.
            contextual=correct.copy(); contextual[2]=2; contextual[3]=1-2/max(3,length); contextual[4]=.30; contextual[6]=1; contextual[12]=1
            update(contextual,[1,1,0,1,0,f,0,0,0,0,0,0,0,0]+[1,1,0,0])
    w=weights()
    (ASSETS/'ranker-baseline.tsv').write_text('# Generated by tools/train_typing_ranker.py; seed 190191; word-disjoint training only\n'+''.join(f'{name}\t{v:.8f}\n' for name,v in zip(FEATURES,w)),encoding='utf-8')
    target=ROOT/'app/src/test/resources/typing-generated.json'
    target.write_text(json.dumps(rows,separators=(',',':')),encoding='utf-8')
    manifest={'seed':190191,'features':FEATURES,'algorithm':'pairwise FTRL-Proximal alpha=.25 beta=1 L1=.01 L2=.25 epochs=8','splitUnit':'SHA256 of intended word; 60/20/20','counts':dict(collections.Counter(r['split'] for r in rows)),'datasetSHA256':hashlib.sha256(target.read_bytes()).hexdigest(),'weights':[round(v,8) for v in w]}
    (ROOT/'tools/typing-training-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
    print(manifest['counts']); print(w)
if __name__ == '__main__': main()
